name: Updater

on:
  schedule:
    - cron: '3 23 * * *'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - source: ohmyzsh/ohmyzsh
            target: ohmyzsh
          - source: testflows/testflows-github-hetzner-runners
            target: testflows-github-hetzner-runners
    steps:
      - run: |
          git clone --bare https://github.com/${{ matrix.source }}.git --single-branch
          cd ${{ matrix.target }}.git
          echo "Clone successful - Starting push"
          git push --mirror https://litetex:${{ secrets.CB_TOKEN }}@codeberg.org/litetex/${{ matrix.target }}.git
          echo "Done"
